// frontend/src/pages/auth/Login.vue
<script setup lang="ts">
import { ref } from "vue";
import { Link, useForm } from "@inertiajs/vue3";
import { Lock, Mail, ArrowRight, Eye, EyeOff } from "lucide-vue-next";
import AuthLayout from "@layouts/AuthLayout.vue";
import type { Flash } from "@lib/types";

interface Props {
  flash?: Flash;
}

defineProps<Props>();

const form = useForm({
  email: "",
  password: "",
});

const showPassword = ref(false);

function submitForm() {
  form.post("/login");
}
</script>

<template>
  <AuthLayout
    title="Sign in"
    subtitle="Enter your credentials to continue"
    headline="Welcome back"
    subheadline="Sign in to continue building amazing applications with the high-performance Go + Svelte framework."
    :stats="[
      { value: '11x', label: 'Faster' },
      { value: '1.5ms', label: 'Latency' },
      { value: '99.9%', label: 'Uptime' },
    ]"
    :flash="flash"
  >
    <a
      href="/auth/google"
      class="w-full flex items-center justify-center gap-3 px-4 py-3 rounded-xl border border-neutral-300 dark:border-white/[0.08] bg-white dark:bg-neutral-800/50 text-neutral-700 dark:text-white font-medium hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-brand-400/50 focus:ring-offset-2 focus:ring-offset-neutral-100 dark:focus:ring-offset-neutral-900"
    >
      <svg class="h-5 w-5" viewBox="0 0 24 24">
        <path
          d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
          fill="#4285F4"
        />
        <path
          d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
          fill="#34A853"
        />
        <path
          d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
          fill="#FBBC05"
        />
        <path
          d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
          fill="#EA4335"
        />
      </svg>
      Continue with Google
    </a>

    <div class="relative my-8">
      <div class="absolute inset-0 flex items-center">
        <div class="w-full border-t border-neutral-200/80 dark:border-white/[0.04]"></div>
      </div>
      <div class="relative flex justify-center">
        <span class="px-4 text-sm text-neutral-500 bg-white dark:bg-neutral-925">or continue with email</span>
      </div>
    </div>

    <form class="space-y-5" @submit.prevent="submitForm">
      <div class="space-y-2">
        <label
          for="email"
          class="block text-sm font-medium text-neutral-700 dark:text-neutral-300"
        >Email</label>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
            <Mail class="w-5 h-5 text-neutral-500" />
          </div>
          <input
            v-model="form.email"
            required
            type="email"
            name="email"
            id="email"
            class="w-full pl-12 pr-4 py-3 rounded-xl bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700/80 text-neutral-900 dark:text-white placeholder-neutral-400 dark:placeholder-neutral-500 focus:outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-400/20 transition-colors duration-200"
            placeholder="you@example.com"
          />
        </div>
      </div>

      <div class="space-y-2">
        <label
          for="password"
          class="block text-sm font-medium text-neutral-700 dark:text-neutral-300"
        >Password</label>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
            <Lock class="w-5 h-5 text-neutral-500" />
          </div>
          <input
            v-model="form.password"
            required
            :type="showPassword ? 'text' : 'password'"
            name="password"
            id="password"
            placeholder="••••••••"
            class="w-full pl-12 pr-12 py-3 rounded-xl bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700/80 text-neutral-900 dark:text-white placeholder-neutral-400 dark:placeholder-neutral-500 focus:outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-400/20 transition-colors duration-200"
          />
          <button
            type="button"
            @click="showPassword = !showPassword"
            class="absolute inset-y-0 right-0 pr-4 flex items-center text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-300 transition-colors"
          >
            <EyeOff v-if="showPassword" class="w-5 h-5" />
            <Eye v-else class="w-5 h-5" />
          </button>
        </div>
      </div>

      <div class="flex justify-end">
        <Link
          href="/forgot-password"
          class="text-sm text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 transition-colors"
        >
          Forgot password?
        </Link>
      </div>

      <button
        type="submit"
        :disabled="form.processing"
        class="w-full py-3 px-4 rounded-xl bg-brand-600 hover:bg-brand-700 text-white font-semibold dark:bg-brand-500 dark:hover:bg-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-400/50 focus:ring-offset-2 focus:ring-offset-neutral-100 dark:focus:ring-offset-neutral-900 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
      >
        <template v-if="form.processing">
          <svg class="animate-spin h-5 w-5" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          Signing in...
        </template>
        <template v-else>
          Sign in
          <ArrowRight class="w-5 h-5" />
        </template>
      </button>
    </form>

    <p class="mt-8 text-center text-sm text-neutral-600 dark:text-neutral-400">
      Don't have an account?
      <Link
        href="/register"
        class="text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 font-medium transition-colors"
      >
        Create one
      </Link>
    </p>
  </AuthLayout>
</template>

// frontend/src/pages/auth/Login.svelte
<script lang="ts">
    import { inertia, useForm } from "@inertiajs/svelte";
    import { Lock, Mail, ArrowRight, Eye, EyeOff } from "lucide-svelte";
    import AuthLayout from "@layouts/AuthLayout.svelte";
    import type { Flash } from "@lib/types";

    const form = useForm({
        email: "",
        password: "",
    });

    let showPassword = $state(false);

    interface Props {
        flash?: Flash;
    }

    let { flash }: Props = $props();

    function submitForm(e: Event) {
        e.preventDefault();
        form.post("/login");
    }
</script>

<AuthLayout
    title="Sign in"
    subtitle="Enter your credentials to continue"
    headline="Welcome back"
    subheadline="Sign in to continue building amazing applications with the high-performance Go + Svelte framework."
    stats={[
        { value: "11x", label: "Faster" },
        { value: "1.5ms", label: "Latency" },
        { value: "99.9%", label: "Uptime" },
    ]}
    {flash}
>
    <a
        href="/auth/google"
        class="w-full flex items-center justify-center gap-3 px-4 py-3 rounded-xl border border-neutral-300 dark:border-white/[0.08] bg-white dark:bg-neutral-800/50 text-neutral-700 dark:text-white font-medium hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-brand-400/50 focus:ring-offset-2 focus:ring-offset-neutral-100 dark:focus:ring-offset-neutral-900"
    >
        <svg class="h-5 w-5" viewBox="0 0 24 24">
            <path
                d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                fill="#4285F4"
            />
            <path
                d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                fill="#34A853"
            />
            <path
                d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                fill="#FBBC05"
            />
            <path
                d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                fill="#EA4335"
            />
        </svg>
        Continue with Google
    </a>

    <div class="relative my-8">
        <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-neutral-200/80 dark:border-white/[0.04]"></div>
        </div>
        <div class="relative flex justify-center">
            <span class="px-4 text-sm text-neutral-500 bg-white dark:bg-neutral-925">or continue with email</span>
        </div>
    </div>

    <form class="space-y-5" onsubmit={submitForm}>
        <div class="space-y-2">
            <label
                for="email"
                class="block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >Email</label>
            <div class="relative">
                <div class="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                    <Mail class="w-5 h-5 text-neutral-500" />
                </div>
                <input
                    bind:value={form.email}
                    required
                    type="email"
                    name="email"
                    id="email"
                    class="w-full pl-12 pr-4 py-3 rounded-xl bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700/80 text-neutral-900 dark:text-white placeholder-neutral-400 dark:placeholder-neutral-500 focus:outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-400/20 transition-colors duration-200"
                    placeholder="you@example.com"
                />
            </div>
        </div>

        <div class="space-y-2">
            <label
                for="password"
                class="block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >Password</label>
            <div class="relative">
                <div class="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                    <Lock class="w-5 h-5 text-neutral-500" />
                </div>
                <input
                    bind:value={form.password}
                    required
                    type={showPassword ? "text" : "password"}
                    name="password"
                    id="password"
                    placeholder="••••••••"
                    class="w-full pl-12 pr-12 py-3 rounded-xl bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700/80 text-neutral-900 dark:text-white placeholder-neutral-400 dark:placeholder-neutral-500 focus:outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-400/20 transition-colors duration-200"
                />
                <button
                    type="button"
                    onclick={() => (showPassword = !showPassword)}
                    class="absolute inset-y-0 right-0 pr-4 flex items-center text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-300 transition-colors"
                >
                    {#if showPassword}
                        <EyeOff class="w-5 h-5" />
                    {:else}
                        <Eye class="w-5 h-5" />
                    {/if}
                </button>
            </div>
        </div>

        <div class="flex justify-end">
            <a
                href="/forgot-password"
                use:inertia
                class="text-sm text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 transition-colors"
            >
                Forgot password?
            </a>
        </div>

        <button
            type="submit"
            disabled={form.processing}
            class="w-full py-3 px-4 rounded-xl bg-brand-600 hover:bg-brand-700 text-white font-semibold dark:bg-brand-500 dark:hover:bg-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-400/50 focus:ring-offset-2 focus:ring-offset-neutral-100 dark:focus:ring-offset-neutral-900 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        >
            {#if form.processing}
                <svg class="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none"></circle>
                    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Signing in...
            {:else}
                Sign in
                <ArrowRight class="w-5 h-5" />
            {/if}
        </button>
    </form>

    <p class="mt-8 text-center text-sm text-neutral-600 dark:text-neutral-400">
        Don't have an account?
        <a
            href="/register"
            use:inertia
            class="text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 font-medium transition-colors"
        >
            Create one
        </a>
    </p>
</AuthLayout>
